# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloweb
  labels:
    app: hello
  annotations:
    fluxcd.io/automated: "true"
spec:
  template:
    spec:
      containers:
      - name: hello-app
        image: gcr.io/saas-brcm/hello-app:v1
        ports:
        - containerPort: 8080
